// @generated by diesel CLI or manually for PostgreSQL/Supabase
// Tables are prefixed with wf_ to coexist with Orus tables

diesel::table! {
    wf_platforms (id) {
        id -> Text,
        name -> Nullable<Text>,
        url -> Text,
        external_id -> Nullable<Text>,
        kind -> Text,
        website_url -> Nullable<Text>,
        logo_url -> Nullable<Text>,
    }
}

diesel::table! {
    wf_accounts (id) {
        id -> Uuid,
        name -> Text,
        account_type -> Text,
        #[sql_name = "group"]
        group_ -> Nullable<Text>,
        currency -> Text,
        is_default -> Bool,
        is_active -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        platform_id -> Nullable<Text>,
        account_number -> Nullable<Text>,
        meta -> Nullable<Jsonb>,
        provider -> Nullable<Text>,
        provider_account_id -> Nullable<Text>,
        is_archived -> Bool,
        tracking_mode -> Text,
    }
}

diesel::table! {
    wf_assets (id) {
        id -> Uuid,
        kind -> Text,
        name -> Nullable<Text>,
        display_code -> Nullable<Text>,
        notes -> Nullable<Text>,
        metadata -> Nullable<Jsonb>,
        is_active -> Bool,
        quote_mode -> Text,
        quote_ccy -> Text,
        instrument_type -> Nullable<Text>,
        instrument_symbol -> Nullable<Text>,
        instrument_exchange_mic -> Nullable<Text>,
        instrument_key -> Nullable<Text>,
        provider_config -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_activities (id) {
        id -> Uuid,
        account_id -> Uuid,
        asset_id -> Nullable<Uuid>,
        activity_type -> Text,
        activity_type_override -> Nullable<Text>,
        source_type -> Nullable<Text>,
        subtype -> Nullable<Text>,
        status -> Text,
        activity_date -> Date,
        settlement_date -> Nullable<Date>,
        quantity -> Nullable<Numeric>,
        unit_price -> Nullable<Numeric>,
        amount -> Nullable<Numeric>,
        fee -> Nullable<Numeric>,
        currency -> Text,
        fx_rate -> Nullable<Numeric>,
        notes -> Nullable<Text>,
        metadata -> Nullable<Jsonb>,
        source_system -> Nullable<Text>,
        source_record_id -> Nullable<Text>,
        source_group_id -> Nullable<Text>,
        idempotency_key -> Nullable<Text>,
        import_run_id -> Nullable<Uuid>,
        is_user_modified -> Bool,
        needs_review -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_quotes (id) {
        id -> Uuid,
        asset_id -> Uuid,
        day -> Date,
        source -> Text,
        open -> Nullable<Numeric>,
        high -> Nullable<Numeric>,
        low -> Nullable<Numeric>,
        close -> Numeric,
        adjclose -> Nullable<Numeric>,
        volume -> Nullable<Int8>,
        currency -> Text,
        notes -> Nullable<Text>,
        created_at -> Timestamptz,
        #[sql_name = "timestamp"]
        timestamp_ -> Timestamptz,
    }
}

diesel::table! {
    wf_quote_sync_state (asset_id) {
        asset_id -> Uuid,
        position_closed_date -> Nullable<Date>,
        last_synced_at -> Nullable<Timestamptz>,
        data_source -> Text,
        sync_priority -> Int4,
        error_count -> Int4,
        last_error -> Nullable<Text>,
        profile_enriched_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_market_data_providers (id) {
        id -> Text,
        name -> Text,
        description -> Text,
        url -> Nullable<Text>,
        priority -> Int4,
        enabled -> Bool,
        logo_filename -> Nullable<Text>,
        last_synced_at -> Nullable<Timestamptz>,
        last_sync_status -> Nullable<Text>,
        last_sync_error -> Nullable<Text>,
    }
}

diesel::table! {
    wf_daily_account_valuation (id) {
        id -> Uuid,
        account_id -> Uuid,
        valuation_date -> Date,
        account_currency -> Text,
        base_currency -> Text,
        fx_rate_to_base -> Numeric,
        cash_balance -> Numeric,
        investment_market_value -> Numeric,
        total_value -> Numeric,
        cost_basis -> Numeric,
        net_contribution -> Numeric,
        calculated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_holdings_snapshots (id) {
        id -> Uuid,
        account_id -> Uuid,
        snapshot_date -> Date,
        currency -> Text,
        positions -> Jsonb,
        cash_balances -> Jsonb,
        cost_basis -> Numeric,
        net_contribution -> Numeric,
        calculated_at -> Timestamptz,
        net_contribution_base -> Numeric,
        cash_total_account_currency -> Numeric,
        cash_total_base_currency -> Numeric,
        source -> Text,
    }
}

diesel::table! {
    wf_import_runs (id) {
        id -> Uuid,
        account_id -> Uuid,
        source_system -> Text,
        run_type -> Text,
        mode -> Text,
        status -> Text,
        started_at -> Timestamptz,
        finished_at -> Nullable<Timestamptz>,
        review_mode -> Text,
        applied_at -> Nullable<Timestamptz>,
        checkpoint_in -> Nullable<Jsonb>,
        checkpoint_out -> Nullable<Jsonb>,
        summary -> Nullable<Jsonb>,
        warnings -> Nullable<Jsonb>,
        error -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_activity_import_profiles (account_id) {
        account_id -> Uuid,
        name -> Text,
        config -> Jsonb,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_brokers_sync_state (account_id, provider) {
        account_id -> Uuid,
        provider -> Text,
        checkpoint_json -> Nullable<Jsonb>,
        last_attempted_at -> Nullable<Timestamptz>,
        last_successful_at -> Nullable<Timestamptz>,
        last_error -> Nullable<Text>,
        last_run_id -> Nullable<Uuid>,
        sync_status -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_taxonomies (id) {
        id -> Uuid,
        name -> Text,
        color -> Text,
        description -> Nullable<Text>,
        is_system -> Bool,
        is_single_select -> Bool,
        sort_order -> Int4,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_taxonomy_categories (id, taxonomy_id) {
        id -> Uuid,
        taxonomy_id -> Uuid,
        parent_id -> Nullable<Uuid>,
        name -> Text,
        key -> Text,
        color -> Text,
        description -> Nullable<Text>,
        sort_order -> Int4,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_asset_taxonomy_assignments (id) {
        id -> Uuid,
        asset_id -> Uuid,
        taxonomy_id -> Uuid,
        category_id -> Uuid,
        weight -> Int4,
        source -> Text,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_goals (id) {
        id -> Uuid,
        title -> Text,
        description -> Nullable<Text>,
        target_amount -> Numeric,
        is_achieved -> Bool,
    }
}

diesel::table! {
    wf_goals_allocation (id) {
        id -> Uuid,
        percent_allocation -> Int4,
        goal_id -> Uuid,
        account_id -> Uuid,
    }
}

diesel::table! {
    wf_contribution_limits (id) {
        id -> Uuid,
        group_name -> Text,
        contribution_year -> Int4,
        limit_amount -> Numeric,
        account_ids -> Nullable<Jsonb>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        start_date -> Nullable<Date>,
        end_date -> Nullable<Date>,
    }
}

diesel::table! {
    wf_ai_threads (id) {
        id -> Uuid,
        title -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        config_snapshot -> Nullable<Jsonb>,
        is_pinned -> Bool,
    }
}

diesel::table! {
    wf_ai_messages (id) {
        id -> Uuid,
        thread_id -> Uuid,
        role -> Text,
        content_json -> Jsonb,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    wf_ai_thread_tags (id) {
        id -> Uuid,
        thread_id -> Uuid,
        tag -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    wf_app_settings (setting_key) {
        setting_key -> Text,
        setting_value -> Text,
    }
}

diesel::table! {
    wf_secrets (secret_key) {
        secret_key -> Text,
        secret_value -> Text,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_health_issue_dismissals (issue_id) {
        issue_id -> Text,
        dismissed_at -> Timestamptz,
        data_hash -> Text,
    }
}

diesel::table! {
    wf_users (id) {
        id -> Uuid,
        email -> Text,
        full_name -> Nullable<Text>,
        avatar_url -> Nullable<Text>,
        preferred_currency -> Nullable<Text>,
        is_active -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
        last_login_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    wf_user_roles (id) {
        id -> Uuid,
        user_id -> Uuid,
        role -> Text,
        created_at -> Timestamptz,
        created_by -> Nullable<Uuid>,
    }
}

diesel::table! {
    wf_sync_cursor (id) {
        id -> Int4,
        cursor -> Int8,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_sync_device_config (device_id) {
        device_id -> Text,
        key_version -> Nullable<Int4>,
        trust_state -> Text,
        last_bootstrap_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    wf_sync_engine_state (id) {
        id -> Int4,
        lock_version -> Int8,
        last_push_at -> Nullable<Timestamptz>,
        last_pull_at -> Nullable<Timestamptz>,
        last_error -> Nullable<Text>,
        consecutive_failures -> Int4,
        next_retry_at -> Nullable<Timestamptz>,
        last_cycle_status -> Nullable<Text>,
        last_cycle_duration_ms -> Nullable<Int8>,
    }
}

diesel::table! {
    wf_sync_entity_metadata (entity, entity_id) {
        entity -> Text,
        entity_id -> Text,
        last_event_id -> Text,
        last_client_timestamp -> Timestamptz,
        last_seq -> Int8,
    }
}

diesel::table! {
    wf_sync_outbox (event_id) {
        event_id -> Text,
        entity -> Text,
        entity_id -> Text,
        op -> Text,
        client_timestamp -> Timestamptz,
        payload -> Jsonb,
        payload_key_version -> Int4,
        sent -> Bool,
        status -> Text,
        retry_count -> Int4,
        next_retry_at -> Nullable<Timestamptz>,
        last_error -> Nullable<Text>,
        last_error_code -> Nullable<Text>,
        device_id -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    wf_sync_applied_events (event_id) {
        event_id -> Text,
        seq -> Int8,
        entity -> Text,
        entity_id -> Text,
        applied_at -> Timestamptz,
    }
}

diesel::table! {
    wf_sync_table_state (table_name) {
        table_name -> Text,
        enabled -> Bool,
        last_snapshot_restore_at -> Nullable<Timestamptz>,
        last_incremental_apply_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    wf_revolut_accounts (id) {
        id -> Uuid,
        revolut_account_id -> Text,
        name -> Text,
        currency -> Text,
        balance -> Numeric,
        state -> Text,
        wf_account_id -> Nullable<Uuid>,
        last_synced_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_revolut_auth_tokens (id) {
        id -> Uuid,
        access_token -> Text,
        refresh_token -> Nullable<Text>,
        token_type -> Text,
        scope -> Nullable<Text>,
        expires_at -> Timestamptz,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    wf_revolut_sync_log (id) {
        id -> Uuid,
        sync_type -> Text,
        status -> Text,
        accounts_synced -> Nullable<Int4>,
        transactions_synced -> Nullable<Int4>,
        error_message -> Nullable<Text>,
        started_at -> Timestamptz,
        completed_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    wf_revolut_transactions (id) {
        id -> Uuid,
        revolut_transaction_id -> Text,
        revolut_account_id -> Text,
        tx_type -> Text,
        state -> Text,
        amount -> Numeric,
        currency -> Text,
        description -> Nullable<Text>,
        merchant_name -> Nullable<Text>,
        merchant_category -> Nullable<Text>,
        reference -> Nullable<Text>,
        completed_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        balance_after -> Nullable<Numeric>,
        wf_activity_id -> Nullable<Uuid>,
        synced_to_activities -> Bool,
    }
}

// Joinable declarations
diesel::joinable!(wf_accounts -> wf_platforms (platform_id));
diesel::joinable!(wf_activities -> wf_accounts (account_id));
diesel::joinable!(wf_activities -> wf_assets (asset_id));
diesel::joinable!(wf_activities -> wf_import_runs (import_run_id));
diesel::joinable!(wf_ai_messages -> wf_ai_threads (thread_id));
diesel::joinable!(wf_ai_thread_tags -> wf_ai_threads (thread_id));
diesel::joinable!(wf_asset_taxonomy_assignments -> wf_assets (asset_id));
diesel::joinable!(wf_asset_taxonomy_assignments -> wf_taxonomies (taxonomy_id));
diesel::joinable!(wf_brokers_sync_state -> wf_accounts (account_id));
diesel::joinable!(wf_brokers_sync_state -> wf_import_runs (last_run_id));
diesel::joinable!(wf_daily_account_valuation -> wf_accounts (account_id));
diesel::joinable!(wf_goals_allocation -> wf_accounts (account_id));
diesel::joinable!(wf_goals_allocation -> wf_goals (goal_id));
diesel::joinable!(wf_holdings_snapshots -> wf_accounts (account_id));
diesel::joinable!(wf_import_runs -> wf_accounts (account_id));
diesel::joinable!(wf_quote_sync_state -> wf_assets (asset_id));
diesel::joinable!(wf_quotes -> wf_assets (asset_id));
diesel::joinable!(wf_revolut_accounts -> wf_accounts (wf_account_id));
diesel::joinable!(wf_revolut_transactions -> wf_activities (wf_activity_id));
diesel::joinable!(wf_taxonomy_categories -> wf_taxonomies (taxonomy_id));
diesel::joinable!(wf_user_roles -> wf_users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    wf_accounts,
    wf_activities,
    wf_activity_import_profiles,
    wf_ai_messages,
    wf_ai_thread_tags,
    wf_ai_threads,
    wf_app_settings,
    wf_asset_taxonomy_assignments,
    wf_assets,
    wf_brokers_sync_state,
    wf_contribution_limits,
    wf_daily_account_valuation,
    wf_goals,
    wf_goals_allocation,
    wf_health_issue_dismissals,
    wf_holdings_snapshots,
    wf_import_runs,
    wf_market_data_providers,
    wf_platforms,
    wf_quote_sync_state,
    wf_quotes,
    wf_revolut_accounts,
    wf_revolut_auth_tokens,
    wf_revolut_sync_log,
    wf_revolut_transactions,
    wf_secrets,
    wf_sync_applied_events,
    wf_sync_cursor,
    wf_sync_device_config,
    wf_sync_engine_state,
    wf_sync_entity_metadata,
    wf_sync_outbox,
    wf_sync_table_state,
    wf_taxonomies,
    wf_taxonomy_categories,
    wf_user_roles,
    wf_users,
);
